---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openedx-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - openedx.<<VAR_CERT_CLUSTER_DOMAIN>>
      secretName: openedx-cert
  rules:
    - host: openedx.<<VAR_CERT_CLUSTER_DOMAIN>>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
