---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: yru-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    matchLabels:
      app: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-np
spec:
  type: NodePort
  selector:
    matchLabels:
      app: echoserver    
  ports:
  - port: 80
    targetPort: 8080
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30007
