apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: yru-demo
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   html;
            index  index.html index.htm;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: yru-demo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        env:
          - name: TEST_USERNAME
            valueFrom:
              secretKeyRef:
                name: nginx-secret
                key: username
          - name: TEST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nginx-secret
                key: password              
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: yru-demo
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: yru-demo
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
