alertmanager:
  generic:
    namespace: monitoring
    enabled: true
    createSecret: true
    config:
      alertNoti:
        slackUrl: ''
        channel: '#yru-openedx-nonprod'
        discardRules:
          - alertname: 'CPUThrottlingHigh'
            namespace: 'monitoring'
          - alertname: 'CPUThrottlingHigh'
            namespace: 'kube-system'            
          - alertname: 'KubeControllerManagerDown|KubeSchedulerDown'

prometheus: {}

alertRules: {}
