apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: google-oidc-secret
spec:
  backendType: gcpSecretsManager
  projectId: <<VAR_PROMETHEUS_SECRET_PROJECT>>
  data:
    - key: <<VAR_PROMETHEUS_SECRET_NAME>> # name of the GCP secret
      version: latest # version of the GCP secret
      name: OKTA_CLIENT_ID # key name in the k8s secret      
      property: OKTA_CLIENT_ID

    - key: <<VAR_PROMETHEUS_SECRET_NAME>>
      version: latest
      name: OKTA_CLIENT_SECRET
      property: OKTA_CLIENT_SECRET

    - key: <<VAR_PROMETHEUS_SECRET_NAME>>
      version: latest
      name: OKTA_TENANT_ID
      property: OKTA_TENANT_ID      
